/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ooslab.mms.ui;

import com.ooslab.mms.logic.MessAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author cliford
 */
public class MorePage extends javax.swing.JPanel {

    /**
     * Creates new form MorePage
     */
    public MorePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newPassField = new javax.swing.JTextField();
        clearDataBtn = new javax.swing.JButton();
        updatePassButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Enter new password:");

        newPassField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        clearDataBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        clearDataBtn.setText("CLEAR STUDENT DATA");
        clearDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDataBtnActionPerformed(evt);
            }
        });

        updatePassButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        updatePassButton.setText("UPDATE");
        updatePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updatePassButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(updatePassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(clearDataBtn)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassButtonActionPerformed
        String password;
        password = newPassField.getText();
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a valid password");
            return;
        }
        if(MessAdmin.login().changePwd(password)){
            JOptionPane.showMessageDialog(this, "Password changed successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Operation failed");
        }
    }//GEN-LAST:event_updatePassButtonActionPerformed

    private void clearDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDataBtnActionPerformed
        if(MessAdmin.login().clearStudentData()){
            JOptionPane.showMessageDialog(this, "Students cleared.");
        } else {
            JOptionPane.showMessageDialog(this, "Operation failed");
        }
    }//GEN-LAST:event_clearDataBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDataBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newPassField;
    private javax.swing.JButton updatePassButton;
    // End of variables declaration//GEN-END:variables
}
